name: Go Vet

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  go-vet:
    name: Go Vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version:  1.21.6 #versi go nya

      - name: Initialize Go Modules
        run: go mod download

      - name: Run go vet
        run: go vet main
