name: Go Report Card

on:
  pull_request:
    branches:
      - main

jobs:
  go-report-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'  # Ganti dengan versi Go yang Anda gunakan

      - name: Install Go Report Card Action
        run: go get -u github.com/gojp/goreportcard/cmd/goreportcard-cli

      - name: Run Go Report Card
        run: goreportcard-cli
