name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Langkah ini menginstal pprof
      - name: Install pprof
        run: go get -u github.com/google/pprof

      # Tambahkan langkah-langkah lain yang diperlukan di sini
